# Generated by Django 3.2 on 2021-04-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RPiParameter',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('save_folder', models.TextField()),
                ('num_of_capture', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
