# Generated by Django 3.2 on 2021-04-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPiCamera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RPiParameter',
            new_name='rpi_parameter',
        ),
    ]
